import type { Conversation, DashboardData, SubmitResponse } from './types';
import type { BackendCase, SessionCreated, FinalEvent, StreamEvent } from './backend';
import { readSse } from './sse';
import { demoConversations, demoDashboard, demoReply } from './demo';
export const config = { mode: import.meta.env.VITE_DATA_MODE === 'api' ? 'api' : 'demo', baseUrl: (import.meta.env.VITE_API_BASE_URL || '/api').replace(/\/$/, '') } as const;
const key='sema-conversations-v1';
const headers=()=>({'Content-Type':'application/json','X-Sema-Access':sessionStorage.getItem('sema-access')||'','X-Request-Id':crypto.randomUUID()});
export const setAccess=(value:string)=>sessionStorage.setItem('sema-access',value);
const sessionIndex:Record<string,Conversation>={};
export class ApiError extends Error { constructor(message:string,public status=0){super(message)} }
export function readDemo():Conversation[]{try{const saved=localStorage.getItem(key);return saved?JSON.parse(saved):demoConversations}catch{return demoConversations}}
function writeDemo(data:Conversation[]){localStorage.setItem(key,JSON.stringify(data));window.dispatchEvent(new Event('sema:data'))}
async function request<T>(path:string,options:RequestInit={}):Promise<T>{
 if(!config.baseUrl)throw new ApiError('VITE_API_BASE_URL təyin edilməyib.');
 const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),20000);
 try{const response=await fetch(`${config.baseUrl}${path}`,{...options,signal:controller.signal,credentials:'include',headers:{...headers(),...options.headers}});if(!response.ok)throw new ApiError(`Sorğu uğursuz oldu (${response.status}).`,response.status);return await response.json() as T}catch(e){if(e instanceof ApiError)throw e;throw new ApiError(e instanceof Error&&e.name==='AbortError'?'Sorğunun vaxtı bitdi. Yenidən cəhd edin.':'Serverə bağlantı alınmadı.')}finally{clearTimeout(timeout)}
}
function mapCase(c:BackendCase):Conversation {return {id:c.case_id,sessionId:c.session_id,title:c.summary||c.intent||c.root_cause,preview:c.root_cause,time:'',status:c.status==='RESOLVED'?'closed':'open',channel:c.channel==='voice'?'call':'text',queue:c.status==='ESCALATED'?'agent':c.status==='OPEN'?'unassigned':'ai',priority:c.priority==='P1'?'urgent':c.priority==='P2'?'high':'normal',customer:c.msisdn.replace(/(\+99498)\d+(\d{4})$/,'$1***$2'),assignee:c.team||undefined,createdAt:c.created_at,waitingMinutes:Math.max(0,Math.floor((Date.now()-Date.parse(c.created_at))/60000)),messages:c.transcript||[],backendCase:c}}
async function cases():Promise<BackendCase[]>{const result=await request<BackendCase[]|{cases:BackendCase[]}>('/v1/cases?limit=250');const list=Array.isArray(result)?result:result.cases;if(!Array.isArray(list)||list.some(c=>!c.case_id||!c.status))throw new ApiError('Backend case formatı müqaviləyə uyğun deyil.');return list}
async function submitStream(text:string,id?:string,onEvent?:(event:StreamEvent)=>void):Promise<SubmitResponse>{
 let c=id?sessionIndex[id]:undefined;if(!c){const created=await request<SessionCreated>('/v1/sessions',{method:'POST',body:JSON.stringify({channel:'web',msisdn:import.meta.env.VITE_DEMO_MSISDN||'+994981001644',verified_level:1,language:'az'})});c={id:created.session_id,sessionId:created.session_id,title:text.slice(0,50),preview:text,time:'İndi',status:'open',channel:'text',messages:[{role:'assistant',text:created.greeting}]};sessionIndex[c.id]=c}
 const session=c.sessionId||c.id;let assembled='',lastId='',final:FinalEvent|undefined,done=false;
 for(let attempt=0;attempt<3&&!done;attempt++){
 const url=attempt===0?`/v1/sessions/${encodeURIComponent(session)}/messages:stream`:`/v1/sessions/${encodeURIComponent(session)}/events`;
 const response=await fetch(`${config.baseUrl}${url}`,{method:attempt===0?'POST':'GET',headers:{...headers(),Accept:'text/event-stream',...(lastId?{'Last-Event-ID':lastId}:{})},body:attempt===0?JSON.stringify({text,client_msg_id:crypto.randomUUID()}):undefined,signal:AbortSignal.timeout(60000)});
 if(!response.ok||!response.body)throw new ApiError(`Stream sorğusu uğursuz oldu (${response.status}).`,response.status);
 try{for await(const frame of readSse(response.body)){if(frame.id&&lastId&&Number(frame.id)<=Number(lastId))continue;if(frame.id)lastId=frame.id;let payload:Record<string,unknown>;try{payload=JSON.parse(frame.data)}catch{throw new ApiError('Stream JSON formatı yanlışdır.')}onEvent?.({event:frame.event,id:frame.id,data:payload});if(frame.event==='delta')assembled+=String(payload.text||'');if(frame.event==='final'){final=payload as unknown as FinalEvent;if(final.text)assembled=final.text}if(frame.event==='error')throw new ApiError(String(payload.message||'Emal xətası'));if(frame.event==='done'){done=true;break}}}catch(e){if(e instanceof ApiError||!lastId||attempt===2)throw e}
 if(!done&&!lastId)throw new ApiError('Stream tamamlanmadı. Avtomatik olaraq yeni maliyyə sorğusu göndərilmir.');
 }
 if(!done)throw new ApiError('Cavab axını tamamlanmadı. Sessiyanı yoxlayın.');
 const result:Conversation={...c,messages:[...c.messages,{role:'user',text},{role:'assistant',text:assembled||'Müraciət qeydə alındı.'}],status:final&&final.decision!=='SPECIALIST'?'closed':'open'};sessionIndex[result.id]=result;return {conversation:result}
}

function realDashboard(raw:BackendCase[]):DashboardData {const closed=raw.filter(c=>c.status==='RESOLVED'),today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Baku'});const daily=new Map<string,{date:string;incoming:number;resolved:number}>();for(const c of raw){const d=c.created_at.slice(0,10);if(!daily.has(d))daily.set(d,{date:d,incoming:0,resolved:0});daily.get(d)!.incoming++;if(c.closed_at){const r=c.closed_at.slice(0,10);if(!daily.has(r))daily.set(r,{date:r,incoming:0,resolved:0});daily.get(r)!.resolved++}}const times=raw.flatMap(c=>c.latency_ms?[c.latency_ms.first_token/1000]:[]).sort((a,b)=>a-b);return {conversations:raw.map(mapCase),volume:[...daily.values()].sort((a,b)=>a.date.localeCompare(b.date)),medianFirstResponseSeconds:times.length?Math.round(times[Math.floor(times.length/2)]):null,resolvedToday:closed.filter(c=>c.closed_at?.startsWith(today)).length,resolution:{ai:closed.filter(c=>!c.team).length,agent:closed.filter(c=>c.team).length,handoff:raw.filter(c=>c.status==='ESCALATED').length}}}
export const supportApi={
 async detail(id:string):Promise<Conversation>{return config.mode==='demo'?readDemo().find(c=>c.id===id)!:mapCase(await request<BackendCase>(`/v1/cases/${encodeURIComponent(id)}`))},
 async conversations():Promise<Conversation[]>{return config.mode==='demo'?readDemo():(await cases()).map(mapCase)},
 async dashboard():Promise<DashboardData>{return config.mode==='demo'?demoDashboard(readDemo()):realDashboard(await cases())},
 async submit(text:string,id?:string,onEvent?:(event:StreamEvent)=>void):Promise<SubmitResponse>{if(config.mode==='api')return submitStream(text,id,onEvent);await new Promise(r=>setTimeout(r,450));const data=readDemo();let c=data.find(c=>c.id===id);if(!c){c={id:crypto.randomUUID(),title:text.slice(0,37),preview:text,time:'İndi',status:'open',channel:'text',queue:'ai',priority:'normal',createdAt:new Date().toISOString(),customer:'Demo müştəri',messages:[]};data.unshift(c)}c={...c,preview:text,time:'İndi',messages:[...c.messages,{role:'user',text},{role:'assistant',text:demoReply(text)}]};writeDemo(data.map(item=>item.id===c.id?c:item));return {conversation:c}},
 async status(id:string,status:Conversation['status']):Promise<Conversation>{if(config.mode==='api')throw new ApiError('Müraciətin statusunu dəyişmək üçün endpoint müqavilədə göstərilməyib.');const data=readDemo();const found=data.find(c=>c.id===id);if(!found)throw new ApiError('Müraciət tapılmadı.');const updated={...found,status};writeDemo(data.map(c=>c.id===id?updated:c));return updated},
 async assign(id:string,assignee:string):Promise<Conversation>{if(config.mode==='api')throw new ApiError('Mütəxəssis təyinatı backend tərəfindən idarə olunur.');const data=readDemo();const found=data.find(c=>c.id===id);if(!found)throw new ApiError('Müraciət tapılmadı.');const updated:Conversation={...found,assignee,queue:'agent'};writeDemo(data.map(c=>c.id===id?updated:c));return updated},
 async saveDemoCall(seconds:number){if(config.mode!=='demo')throw new ApiError('Real zəng xidməti hələ inteqrasiya edilməyib.');const c:Conversation={id:crypto.randomUUID(),title:'Səsli müraciət',preview:`Demo zəng · ${seconds} saniyə`,time:'İndi',status:'closed',channel:'call',queue:'ai',priority:'normal',messages:[{role:'assistant',text:`Demo zəng ${seconds} saniyə davam etdi. Real səs ötürülməyib.`}]};writeDemo([c,...readDemo()]);return c}
};
