import {createContext,useContext,useEffect,useRef,useState,type ReactNode} from 'react';
import {Menu,X,Phone,MessageSquare,LayoutDashboard} from 'lucide-react';
import {LanguageSwitcher} from './LanguageSwitcher';
import {ThemeSwitcher} from './ThemeSwitcher';
import {t} from '../lib/i18n';
import {supportApi} from '../lib/api';
import {demoLines} from '../lib/usage';
import {Button} from './ui/button';
interface ShellState{setBusy:(busy:boolean)=>void}
const ShellContext=createContext<ShellState>({setBusy:()=>{}});
export const useShell=()=>useContext(ShellContext);
interface Props{page:'support'|'dashboard';navigate:(page:'support'|'dashboard')=>void;prefetch:(page:'support'|'dashboard')=>void;children:ReactNode}
export function AppShell({page,navigate,prefetch,children}:Props){
 const [busy,setBusy]=useState(false);const [open,setOpen]=useState(false);const [demo,setDemo]=useState(false);const [scrolled,setScrolled]=useState(false);const [online,setOnline]=useState(navigator.onLine);const dialog=useRef<HTMLDialogElement>(null);const menuButton=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const scroll=()=>setScrolled(scrollY>4);const connected=()=>setOnline(navigator.onLine);window.addEventListener('scroll',scroll,{passive:true});window.addEventListener('online',connected);window.addEventListener('offline',connected);return()=>{window.removeEventListener('scroll',scroll);window.removeEventListener('online',connected);window.removeEventListener('offline',connected)}},[]);
 useEffect(()=>{const node=dialog.current;if(!node)return;if(open){node.showModal();const prior=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{node.close();document.body.style.overflow=prior;menuButton.current?.focus()}}},[open]);
 const go=(target:'support'|'dashboard')=>{if(busy)return;setOpen(false);setDemo(false);navigate(target)};
 const nav=<nav aria-label={t('navigation.mainLabel')}>{(['support','dashboard'] as const).map(target=><Button key={target} variant="ghost" disabled={busy} aria-current={page===target?'page':undefined} onMouseEnter={()=>prefetch(target)} onFocus={()=>prefetch(target)} onClick={()=>go(target)}>{target==='support'?<MessageSquare size={17}/>:<LayoutDashboard size={17}/>} {t(target==='support'?'navigation.support':'navigation.dashboard')}</Button>)}</nav>;
 return <ShellContext.Provider value={{setBusy}}><a className="skip-link" href="#main-content" onClick={e=>{e.preventDefault();document.getElementById('main-content')?.focus()}}>{t('common.skipContent')}</a><header className={`app-header ${scrolled?'is-scrolled':''}`}><div className="brand"><img className="brand-logo" src="/logo.svg" alt=""/><span>{t('brand.productName').split(' ')[0]}<span className="brand-dot"> Mobile</span></span><span className="agent-label">{t('brand.assistantName')}</span></div><div className="desktop-nav">{nav}</div><div className="header-tools"><div className="demo-menu"><Button variant="outline" disabled={busy} aria-expanded={demo} onClick={()=>setDemo(v=>!v)}>{t('support.demoCustomerLabel')}</Button>{demo&&<div className="demo-menu-panel"><label>{t('support.demoCustomerLabel')}<select autoFocus aria-label={t('support.demoCustomerLabel')} value={supportApi.getCustomer()} onChange={e=>{const msisdn=e.target.value;supportApi.chooseCustomer(msisdn);setDemo(false);window.dispatchEvent(new CustomEvent('sama:customer',{detail:msisdn}));if(page==='dashboard')go('support')}}>{demoLines.map(([phone,name])=><option key={phone} value={phone}>{name}</option>)}</select><Button variant="ghost" onClick={()=>setDemo(false)}>{t('common.close')}</Button></label></div>}</div><LanguageSwitcher/><ThemeSwitcher/><Button ref={menuButton} className="mobile-menu-toggle" variant="ghost" size="icon" aria-label={t('navigation.menu')} aria-expanded={open} onClick={()=>setOpen(true)}><Menu size={22}/></Button></div></header>{!online&&<div className="offline-banner" role="status">{t('common.offline')}<Button variant="ghost" onClick={()=>location.reload()}>{t('common.retry')}</Button></div>}{children}<dialog ref={dialog} className="mobile-navigation" aria-label={t('navigation.menu')} onCancel={()=>setOpen(false)} onClose={()=>setOpen(false)} onClick={e=>{if(e.target===e.currentTarget)setOpen(false)}}><Button variant="ghost" size="icon" onClick={()=>setOpen(false)} aria-label={t('common.close')}><X size={22}/></Button><strong>{t('brand.productName')}</strong>{nav}<Button variant="outline" disabled={busy} onClick={()=>{sessionStorage.setItem('sama-open-call','1');go('support');window.dispatchEvent(new Event('sama:call'))}}><Phone size={18}/>{t('voice.call')}</Button></dialog></ShellContext.Provider>
}
