import {useEffect,useRef} from 'react';
import type {ManagedVoiceSession} from '../lib/managed-voice';
export function VoiceRing({getSession,phase,muted}:{getSession:()=>ManagedVoiceSession|null;phase:string;muted:boolean}){
 const canvas=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{const el=canvas.current;if(!el)return;const ctx=el.getContext('2d');if(!ctx)return;let frame=0;let alive=true;let colors=['',''];const bins=Array(48).fill(0) as number[];const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const theme=()=>{const style=getComputedStyle(el);colors=[style.getPropertyValue('--accent').trim(),style.getPropertyValue('--voice-secondary').trim()]};theme();const observer=new MutationObserver(theme);observer.observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});
 const draw=()=>{if(!alive)return;const width=el.clientWidth;const height=el.clientHeight;const dpr=Math.min(devicePixelRatio||1,2);if(el.width!==Math.round(width*dpr)||el.height!==Math.round(height*dpr)){el.width=Math.round(width*dpr);el.height=Math.round(height*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,width,height);const session=getSession();const speaking=phase==='speaking';const data=session?(speaking?session.getOutputByteFrequencyData():muted?null:session.getInputByteFrequencyData()):null;const radius=Math.min(width,height)*.41;const center=[width/2,height/2];ctx.strokeStyle=speaking?colors[0]:colors[1];ctx.globalAlpha=.3;ctx.lineWidth=1;ctx.beginPath();ctx.arc(center[0],center[1],radius,0,Math.PI*2);ctx.stroke();const count=reduced.matches?1:48;for(let i=0;i<count;i++){const v=data?(data[Math.floor((i<24?i:47-i)/24*data.length)]||0)/255:0;bins[i]+=(v-bins[i])*(v>bins[i]?.55:.12);if(reduced.matches){ctx.globalAlpha=.35+bins[i]*.5;ctx.lineWidth=2+bins[i]*5;ctx.beginPath();ctx.arc(center[0],center[1],radius,0,Math.PI*2);ctx.stroke();continue}const angle=i/count*Math.PI*2-Math.PI/2;const length=3+bins[i]*22;ctx.globalAlpha=.35+bins[i]*.6;ctx.lineWidth=2.5;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(center[0]+Math.cos(angle)*radius,center[1]+Math.sin(angle)*radius);ctx.lineTo(center[0]+Math.cos(angle)*(radius+length),center[1]+Math.sin(angle)*(radius+length));ctx.stroke()}frame=requestAnimationFrame(draw)};frame=requestAnimationFrame(draw);return()=>{alive=false;cancelAnimationFrame(frame);observer.disconnect()}
 },[getSession,phase,muted]);
 return <canvas ref={canvas} className={`voice-ring ${phase==='connecting'||phase==='thinking'?'voice-ring-thinking':''}`} aria-hidden="true"/>;
}
