import test from 'node:test';import assert from 'node:assert/strict';import handler from '../netlify/edge-functions/sema-api.js';
const values={SEMA_BACKEND_URL:'https://backend.example.test',SEMA_API_KEY:'server-only-test-key',SEMA_ACCESS_TOKEN:'test-access',SEMA_DEMO_MSISDN:'+994981001644'};
globalThis.Netlify={env:{get:key=>values[key]}};
test('proxy rejects unauthenticated and unsupported administrative requests',async()=>{assert.equal((await handler(new Request('https://site.test/api/v1/cases'))).status,401);assert.equal((await handler(new Request('https://site.test/api/v1/admin/reset-demo',{method:'POST',headers:{'x-sema-access':'test-access'},body:'{}'}))).status,403)});
test('proxy keeps key server-side and forces configured demo identity',async()=>{const original=globalThis.fetch;let target,options;globalThis.fetch=async(u,o)=>{target=u;options=o;return new Response('{"session_id":"ss_test"}',{headers:{'content-type':'application/json'}})};try{const res=await handler(new Request('https://site.test/api/v1/sessions',{method:'POST',headers:{'x-sema-access':'test-access',origin:'https://site.test'},body:JSON.stringify({msisdn:'+994981009999',verified_level:2,language:'ru'})}));assert.equal(res.status,200);assert.equal(String(target),'https://backend.example.test/v1/sessions');assert.equal(options.headers.get('X-API-Key'),'server-only-test-key');assert.equal(JSON.parse(options.body).msisdn,values.SEMA_DEMO_MSISDN);assert.equal(JSON.parse(options.body).verified_level,1);assert.equal(res.headers.get('X-API-Key'),null)}finally{globalThis.fetch=original}});
test('proxy forwards event cursor and streaming body',async()=>{const original=globalThis.fetch;globalThis.fetch=async(u,o)=>{assert.equal(o.headers.get('Last-Event-ID'),'17');return new Response('event: done\ndata: {}\n\n',{headers:{'content-type':'text/event-stream'}})};try{const res=await handler(new Request('https://site.test/api/v1/sessions/ss_test/events',{headers:{'x-sema-access':'test-access','last-event-id':'17'}}));assert.match(await res.text(),/event: done/)}finally{globalThis.fetch=original}});
test('public proxy connects without a visitor key and accepts only a listed demo identity',async()=>{const original=globalThis.fetch;const access=values.SEMA_ACCESS_TOKEN;delete values.SEMA_ACCESS_TOKEN;let requests=0;globalThis.fetch=async(u,o)=>{requests++;assert.equal(o.headers instanceof Headers?o.headers.get('X-API-Key'):o.headers['X-API-Key'],'server-only-test-key');if(String(u).endsWith('/v1/demo/cases'))return new Response(JSON.stringify({cases:[{msisdn:'+994981000548'}]}));assert.equal(JSON.parse(o.body).msisdn,'+994981000548');return new Response('{"session_id":"test"}')};try{const make=msisdn=>new Request('https://site.test/api/v1/sessions',{method:'POST',headers:{origin:'https://site.test'},body:JSON.stringify({msisdn})});assert.equal((await handler(make('+994981000548'))).status,200);assert.equal((await handler(make('+994501111111'))).status,400);assert.equal(requests,3)}finally{globalThis.fetch=original;values.SEMA_ACCESS_TOKEN=access}});
test('usage endpoints forward encoded line, six-month query and server-only key',async()=>{const original=globalThis.fetch;const seen=[];globalThis.fetch=async(u,o)=>{seen.push(String(u));assert.equal(o.headers.get('X-API-Key'),'server-only-test-key');return new Response('{"currency":"AZN","months":[]}')};try{for(const path of ['/v1/lines/%2B994981000137/usage?months=6','/v1/usage/summary?months=6']){const response=await handler(new Request('https://site.test/api'+path,{headers:{'x-sema-access':'test-access'}}));assert.equal(response.status,200);assert.equal(response.headers.get('X-API-Key'),null)}assert.deepEqual(seen,['https://backend.example.test/v1/lines/%2B994981000137/usage?months=6','https://backend.example.test/v1/usage/summary?months=6'])}finally{globalThis.fetch=original}});
test('public usage reads are limited to demo lines and bounded month query',async()=>{const access=values.SEMA_ACCESS_TOKEN;delete values.SEMA_ACCESS_TOKEN;try{for(const [path,status] of [['/v1/lines/%2B994981009999/usage?months=6',404],['/v1/usage/summary?months=99',400],['/v1/usage/summary?months=6&admin=1',400]])assert.equal((await handler(new Request('https://site.test/api'+path))).status,status)}finally{values.SEMA_ACCESS_TOKEN=access}});
