import test from 'node:test';import assert from 'node:assert/strict';
import {VoiceSessionOwner} from '../src/lib/voice-session.ts';
import {brandText} from '../src/lib/branding.ts';
const session=()=>{const calls=[];return {calls,setMicMuted:v=>calls.push(['mute',v]),endSession:async()=>calls.push(['end'])}};
test('microphone toggle reaches the session and ending mutes before releasing it',async()=>{const owner=new VoiceSessionOwner();const s=session();await owner.start(async()=>s);assert.equal(await owner.mute(true),true);await owner.mute(false);await owner.stop();assert.deepEqual(s.calls,[['mute',true],['mute',false],['mute',true],['end']]);assert.equal(owner.session,null);assert.equal(await owner.mute(false),false)});
test('cancelled or unmounted pending call is muted and closed when it resolves',async()=>{const owner=new VoiceSessionOwner();const s=session();let resolve;const pending=owner.start(()=>new Promise(r=>resolve=r));await owner.stop();resolve(s);assert.equal(await pending,null);assert.deepEqual(s.calls,[['mute',true],['end']]);assert.equal(owner.session,null)});
test('stale connection cannot replace a newer session',async()=>{const owner=new VoiceSessionOwner();let resolve;const a=session(),b=session();const old=owner.start(()=>new Promise(r=>resolve=r));await owner.stop();await owner.start(async()=>b);resolve(a);await old;assert.equal(owner.session,b);assert.deepEqual(a.calls,[['mute',true],['end']]);await owner.stop()});
test('legacy assistant names are migrated without replacing unrelated words',()=>{assert.equal(brandText('Salam, mən Ayla, Səma Mobile. Sama Care.'),'Salam, mən Maryam Agent, Sama Mobile. Sama Mobile.');assert.equal(brandText('Aylas, 5 AZN, R-3.2'),'Aylas, 5 AZN, R-3.2')});
test('ending still releases the session if muting fails',async()=>{const owner=new VoiceSessionOwner();let ended=false;await owner.start(async()=>({setMicMuted(){throw new Error('mute failed')},async endSession(){ended=true}}));await assert.rejects(owner.stop(),/mute failed/);assert.equal(ended,true);assert.equal(owner.session,null)});

test('assistant display migrates old product names in AZ while retaining the agent identity',()=>{assert.equal(brandText('Maryam Care · Sama Mobile · Maryam Agent','az'),'Səma Mobile · Səma Mobile · Məryəm Agent');assert.equal(brandText('Məryəm Agent · Səma Mobile','ru'),'Maryam Agent · Sama Mobile')});
