import { useEffect, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, Download, Headphones, LoaderCircle, MessageSquare, Sparkles } from 'lucide-react';
import { LanguageSwitcher } from '../components/LanguageSwitcher';
import { getLocale, t } from '../lib/i18n';
import { supportApi, ApiError } from '../lib/api';
import { brandText } from '../lib/ui-branding';
import { categoryIcons, chronological, costKeys, demoLines, limitPercent, maskLine, nonZeroCosts, progressTone, type Category, type CostKey, type LineUsageResponse, type SummaryResponse, type UsageMonth, type SummaryMonth } from '../lib/usage';
import './dashboard.css';
export interface SupportRequest{msisdn:string;text:string}
const colors=Array.from({length:6},(_,i)=>`var(--chart-${i+1})`);
const numericLocale=()=>getLocale()==='az'?'ru-RU':getLocale()==='ru'?'ru-RU':'en-GB';
const money=(n:number)=>`${new Intl.NumberFormat(numericLocale(),{minimumFractionDigits:2,maximumFractionDigits:2}).format(n)} ₼`;
const number=(n:number)=>new Intl.NumberFormat(numericLocale(),{maximumFractionDigits:1}).format(n);
const gb=(n:number)=>n>=1024?`${new Intl.NumberFormat(numericLocale(),{minimumFractionDigits:1,maximumFractionDigits:1}).format(n/1024)} GB`:`${number(n)} MB`;
// Month is a calendar identifier, not a browser-time-zone timestamp. Explicit labels also support browsers without az Intl data.
const monthName=(month:string)=>`${t(`usage.monthNames.${Number(month.slice(5,7))-1}`)} ${month.slice(0,4)}`;
function Progress({label,value,limit,pct,unit}:{label:string;value:string;limit:string;pct:number|null;unit?:string}){return <div className={`usage-meter ${progressTone(pct)}`}><div><span>{label}</span><strong>{value}{unit} <small>/ {limit}{unit}</small></strong></div><div className="usage-meter-track" role="progressbar" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={pct==null?undefined:Math.min(100,pct)} aria-valuetext={pct==null?t('usage.noPackage'):t('usage.percentUsed',{pct:number(pct)})}><i style={{width:`${Math.min(100,Math.max(0,pct||0))}%`}}/></div><small>{pct==null?t('usage.noPackage'):t('usage.percentUsed',{pct:number(pct)})}</small></div>}
function Categories({data}:{data:Partial<Record<Category,number>>}){const items=Object.entries(data).filter(([,value])=>(value||0)>0).sort((a,b)=>(b[1]||0)-(a[1]||0));const max=Math.max(1,...items.map(([,v])=>v||0));return <div className="category-list">{items.map(([key,value])=><div key={key}><span>{categoryIcons[key as Category]} {t(`usage.categories.${key}`)}</span><strong>{gb(value||0)}</strong><i style={{width:`${(value||0)/max*100}%`}}/></div>)}{!items.length&&<p className="usage-empty">{t('usage.noData')}</p>}</div>}
function CostList({costs}:{costs:Record<CostKey,number>}){const items=nonZeroCosts(costs);const max=Math.max(1,...items.map(item=>item.value));return <div className="cost-list">{items.map(({key,value})=><div key={key}><div><i style={{background:colors[costKeys.indexOf(key)]}}/><span>{t(`usage.costs.${key}`)}</span><strong>{money(value)}</strong></div><div className="cost-track"><i style={{width:`${value/max*100}%`,background:colors[costKeys.indexOf(key)]}}/></div></div>)}{!items.length&&<p className="usage-empty">{t('usage.noCosts')}</p>}</div>}
function HistoryChart({months,summary=false}:{months:(UsageMonth|SummaryMonth)[];summary?:boolean}){const points=chronological(months);const max=Math.max(1,...points.map(m=>'total'in m?Math.max(m.total,m.forecast_total):m.revenue_total));return <><div className="chart-legend"><span><i className="incoming"/>{t(summary?'usage.costStructure':'usage.actualCost')}</span><span><i className="resolved"/>{t('usage.returned')}</span>{!summary&&<small>{t('usage.forecastLegend')}</small>}</div><div className="expense-chart"><svg viewBox="0 0 720 250" role="img" aria-label={t('usage.history')}>
 {Array.from({length:5},(_,i)=><g key={i}><line x1="64" x2="704" y1={30+i*43} y2={30+i*43} stroke="var(--border)"/><text x="4" y={34+i*43} fill="var(--muted)" fontSize="11">{number(max*(1-i/4))}</text></g>)}
 {points.map((m,i)=>{const x=85+i*610/Math.max(points.length,1);const width=Math.min(48,400/Math.max(points.length,1));const line='total'in m?m:null;const costs='cost_breakdown'in m?m.cost_breakdown:null;let cumulative=0;return <g key={m.month} tabIndex={0} aria-label={`${monthName(m.month)}: ${money(line?line.total:(m as SummaryMonth).revenue_total)}, ${t('usage.returned')}: ${money(m.credits_total)}`}><title>{monthName(m.month)} · {money(line?line.total:(m as SummaryMonth).revenue_total)} · {t('usage.returned')} {money(m.credits_total)}{line?.is_current?` · ${t('usage.forecast')} ${money(line.forecast_total)}`:''}</title>{line?.is_current&&<rect x={x-3} y={202-line.forecast_total/max*172} width={width+6} height={line.forecast_total/max*172} rx="5" fill="var(--chart-ghost)" stroke="var(--chart-1)" strokeDasharray="4 4"/>}{line?<rect x={x} y={202-line.total/max*172} width={width} height={line.total/max*172} rx="4" fill="var(--chart-1)"/>:costKeys.map(key=>{const value=costs?.[key]||0;const y=202-(cumulative+value)/max*172;cumulative+=value;return <rect key={key} x={x} y={y} width={width} height={value/max*172} fill={colors[costKeys.indexOf(key)]}/>})}<rect x={x+width+4} y={202-m.credits_total/max*172} width="7" height={m.credits_total/max*172} rx="3" fill="var(--chart-2)"/><text x={x+width/2} y="229" fill="var(--muted)" fontSize="11" textAnchor="middle">{m.month.slice(5)} / {m.month.slice(2,4)}</text></g>})}
 </svg></div></>}
function DailyChart({month}:{month:UsageMonth}){const max=Math.max(1,...month.daily_data_mb);return <><div className="daily-bars" role="img" aria-label={t('usage.daily')} >{month.daily_data_mb.map((value,i)=><div key={i} tabIndex={0} className={month.peak_day===i+1?'peak':''} style={{height:`${Math.max(2,value/max*100)}%`}} aria-label={`${i+1}: ${gb(value)}`}><span>{i+1}: {gb(value)}</span></div>)}</div>{!month.daily_data_mb.length&&<p className="usage-empty">{t('usage.noData')}</p>}{month.peak_day!=null&&<p className="usage-muted">{t('usage.peakDay',{day:month.peak_day})}</p>}</>}
function SummaryTrend({months}:{months:SummaryMonth[]}){const rows=chronological(months);const maxAvg=Math.max(1,...rows.map(m=>m.avg_total)),maxCredits=Math.max(1,...rows.map(m=>m.credits_total));const coords=(value:number,max:number,i:number)=>`${40+i*600/Math.max(1,rows.length-1)},${180-value/max*150}`;return <><div className="chart-legend"><span><i className="incoming"/>{t('usage.averageBill')}</span><span><i className="resolved"/>{t('usage.returned')}</span><small>{t('usage.separateScales')}</small></div><svg className="summary-trend" viewBox="0 0 700 220" role="img" aria-label={t('usage.trend')}><text x="0" y="16" fill="var(--chart-1)" fontSize="11">{money(maxAvg)}</text><text x="640" y="16" fill="var(--chart-2)" fontSize="11">{money(maxCredits)}</text>{['avg_total','credits_total'].map((key,index)=><path key={key} d={rows.map((m,i)=>`${i?'L':'M'}${coords(m[key as 'avg_total'],index?maxCredits:maxAvg,i)}`).join(' ')} stroke={index?'var(--chart-2)':'var(--chart-1)'} fill="none" strokeWidth="3"/>)}{rows.map((m,i)=><g key={m.month}><circle cx={40+i*600/Math.max(1,rows.length-1)} cy={180-m.avg_total/maxAvg*150} r="5" fill="var(--chart-1)"><title>{monthName(m.month)}: {t('usage.averageBill')} {money(m.avg_total)}; {t('usage.returned')} {money(m.credits_total)}</title></circle><text x={40+i*600/Math.max(1,rows.length-1)} y="208" fill="var(--muted)" textAnchor="middle" fontSize="11">{m.month.slice(5)}</text></g>)}</svg></>}
export default function Dashboard({onSupport}:{onSupport:(request?:SupportRequest)=>void}){
 const [mode,setMode]=useState<'line'|'summary'>('line');const [msisdn,setMsisdn]=useState(()=>supportApi.getCustomer());const [line,setLine]=useState<LineUsageResponse|null>(null);const [summary,setSummary]=useState<SummaryResponse|null>(null);const [selectedMonth,setSelectedMonth]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [revision,setRevision]=useState(0);const [period,setPeriod]=useState(6);
 useEffect(()=>{let live=true;setLoading(true);setError('');setLine(null);setSummary(null);setSelectedMonth('');const request=mode==='line'?supportApi.lineUsage(msisdn,6):supportApi.usageSummary(6);request.then(data=>{if(!live)return;if('msisdn'in data)setLine(data);else setSummary(data);setSelectedMonth(data.months[0]?.month||'')}).catch(e=>{if(!live)return;setError(e instanceof ApiError&&e.message==='usage.mockMissing'?'usage.mockMissing':e instanceof ApiError&&e.status===401?'usage.authError':e instanceof ApiError&&e.status===404?'usage.notFound':e instanceof Error&&e.message.startsWith('usage.')?e.message:'usage.loadError')}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[mode,msisdn,revision]);
 const months=mode==='line'?line?.months:summary?.months;const current=mode==='line'&&line&&line.msisdn===msisdn?line.months.find(m=>m.month===selectedMonth):undefined;const aggregate=mode==='summary'?summary?.months.find(m=>m.month===selectedMonth):undefined;const m=current;const s=aggregate;const selected=m||s;
 function csv(){if(!months)return;const escape=(v:unknown)=>`"${String(v??'').replace(/"/g,'""').replace(/^[=+@-]/,"'")}"`;const rows=[[t('usage.month'),t('usage.actualCost'),t('usage.returned'),t('usage.forecast'),t('usage.netCost')],...months.map(m=>'total'in m?[m.month,m.total,m.credits_total,m.forecast_total,m.net_total]:[m.month,m.revenue_total,m.credits_total,'',m.revenue_total-m.credits_total])];const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(row=>row.map(escape).join(',')).join('\n')],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='sama-mobile-usage.csv';a.click();URL.revokeObjectURL(url)}
 const discuss=(text:string)=>{supportApi.chooseCustomer(msisdn);onSupport({msisdn,text})};
 return <div className="dashboard-shell usage-dashboard"><nav className="usage-mode-nav" aria-label={t('navigation.mainLabel')}><button className={mode==='line'?'active':''} aria-pressed={mode==='line'} onClick={()=>setMode('line')}>{t('usage.myExpenses')}</button><button className={mode==='summary'?'active':''} aria-pressed={mode==='summary'} onClick={()=>setMode('summary')}>{t('usage.summary')}</button><button disabled={!months?.length||loading} onClick={csv}>{t('navigation.report')}<Download size={15}/></button></nav>
 <div className="usage-controls">{mode==='line'&&<label><span>{t('support.demoCustomerLabel')}</span><select value={msisdn} onChange={e=>{setMsisdn(e.target.value);supportApi.chooseCustomer(e.target.value)}}>{demoLines.map(([phone,name])=><option key={phone} value={phone}>{name} · {maskLine(phone)}</option>)}</select></label>}{!!months?.length&&!loading&&<label><span>{t('usage.month')}</span><select value={selectedMonth} onChange={e=>setSelectedMonth(e.target.value)}>{months.map(m=><option key={m.month} value={m.month}>{monthName(m.month)}{m.is_current?` · ${t('usage.current')}`:''}</option>)}</select></label>}<span>{import.meta.env.VITE_USE_MOCK==='1'?t('usage.mockSource'):t('usage.apiSource')}</span></div>
 {loading&&<div className="usage-skeleton" aria-busy="true"><p><LoaderCircle size={17}/>{t('common.loading')}</p><div/><div/><div/></div>}{!loading&&error&&<div className="dash-error" role="alert">{t(error)}<button onClick={()=>setRevision(n=>n+1)}>{t('common.retry')}</button></div>}{!loading&&!error&&!selected&&<div className="dash-loading">{t('usage.noData')}</div>}
 {!loading&&!error&&selected&&<><section className="dash-overview"><div className="dash-welcome"><h1>{m?m.full_name:t('usage.summaryHeading')}</h1><p>{m?`${brandText(m.tariff_name)} · ${maskLine(m.msisdn)} · ${m.region}`:t('usage.summaryDescription')}</p><div className="usage-total"><strong>{money(m?m.total:s!.revenue_total)}</strong><span>{t(m?'usage.thisMonth':'usage.revenue')}</span>{m&&m.change_pct!=null&&<small className={m.change_pct>0?'increase':'decrease'}>{m.change_pct>0?<ArrowUpRight size={14}/>:<ArrowDownRight size={14}/>} {number(Math.abs(m.change_pct))}% {t('usage.comparedPrevious')}</small>}</div>{m&&<div className="month-progress"><div><span>{monthName(m.month)}</span><span>{t('usage.elapsedDays',{elapsed:m.days_elapsed,total:m.days_in_month})}</span></div><div><i style={{width:`${Math.min(100,m.days_elapsed/Math.max(1,m.days_in_month)*100)}%`}}/></div></div>}</div>
 <div className={`dash-kpis ${s?'summary-kpis':''}`}>{m?<><div><small>{t(m.is_current?'usage.forecast':'usage.actualCost')}</small><strong>{money(m.is_current?m.forecast_total:m.total)}</strong><p>{t(m.is_current?'usage.monthEndEstimate':'usage.completedMonth')}</p></div><div><small>{t('usage.returned')}</small><strong>{money(m.credits_total)}</strong><p>{t('usage.creditedBack')}</p></div><div><small>{t('usage.netCost')}</small><strong>{money(m.net_total)}</strong><p>{t('usage.afterCredits')}</p></div></>:<><div><small>{t('usage.subscribers')}</small><strong>{s!.lines}</strong><p>{t('usage.lines')}</p></div><div><small>{t('usage.averageBill')}</small><strong>{money(s!.avg_total)}</strong><p>{t('usage.perLine')}</p></div><div><small>{t('usage.returned')}</small><strong>{money(s!.credits_total)}</strong><p>{t('usage.creditCount',{count:s!.credits_count})}</p></div><div><small>{t('usage.savings')}</small><strong>{money(s!.potential_savings_total)}</strong><p>{t('usage.monthlyOpportunity')}</p></div></>}<span className="dash-data-note">{monthName(selected.month)}</span></div></section>
 {m&&m.credits.length>0&&m.credits_total>0&&<section className="usage-credit-banner"><img src="/logo.svg" alt=""/><div><h2>{t('usage.refundHeading',{amount:money(m.credits_total)})}</h2>{m.credits.map((credit,i)=><p key={i}>{credit.reason} <strong>{money(credit.amount)}</strong></p>)}</div></section>}
 <section className="dash-middle"><div className="volume-panel"><aside className="queue-summary"><h2>{t('usage.costBreakdown')}</h2><CostList costs={m?m.costs:s!.cost_breakdown}/></aside><div className="chart-panel"><div className="chart-header"><h2>{t('usage.history')}</h2><div className="period-selector" aria-label={t('usage.chartPeriod')}>{[6,3,1].map(n=><button key={n} className={period===n?'active':''} aria-pressed={period===n} onClick={()=>setPeriod(n)}>{t('usage.months',{count:n})}</button>)}</div></div><HistoryChart months={months!.slice(0,period)} summary={!!s}/>{m&&m.is_current&&<p className="usage-muted">{t('usage.forecastNote')}</p>}</div></div>
 <div className="assignment-card forecast-card"><div><h2>{t(m?(m.is_current?'usage.monthEnd':'usage.completedMonth'):'usage.savings')}</h2><span><Sparkles size={21}/></span></div><strong>{money(m?(m.is_current?m.forecast_total:m.total):s!.potential_savings_total)}</strong><p>{t(m?(m.is_current?'usage.forecastNote':'usage.afterCredits'):'usage.monthlyOpportunity')}</p><div className="usage-paper"><span>{t(m?'usage.actualCost':'usage.averageData')}</span><b>{m?money(m.total):gb(s!.avg_data_mb)}</b></div><div className="usage-paper"><span>{t(m?'usage.netCost':'usage.averageVoice')}</span><b>{m?money(m.net_total):`${number(s!.avg_voice_min)} ${t('usage.minutes')}`}</b></div></div></section>
 <section className="dash-bottom usage-bottom"><div className="dash-card"><div className="card-heading"><h2>{t(m?'usage.packageUsage':'usage.tariffMix')}</h2></div>{m?<><Progress label={t('usage.internet')} value={gb(m.usage.data_mb)} limit={m.usage.data_limit_mb?gb(m.usage.data_limit_mb):'—'} pct={m.usage.data_pct}/><Progress label={t('usage.voiceMinutes')} value={number(m.usage.voice_min)} limit={m.usage.voice_limit_min?number(m.usage.voice_limit_min):'—'} pct={m.usage.voice_pct} unit={` ${t('usage.minutes')}`}/><Progress label="SMS" value={number(m.usage.sms)} limit={m.usage.sms_limit?number(m.usage.sms_limit):'—'} pct={limitPercent(m.usage.sms,m.usage.sms_limit)}/>{m.usage.data_pct==null&&<p className="usage-muted">{t('usage.payg')}</p>}{m.is_current&&<p className="usage-muted">{t('usage.partialMonth')}</p>}</>:<TariffMix mix={s!.tariff_mix}/>}</div>
 <div className="dash-card"><div className="card-heading"><h2>{t('usage.internetCategories')}</h2>{m?.top_category&&<small>{categoryIcons[m.top_category]} {t(`usage.categories.${m.top_category}`)}</small>}</div><Categories data={m?m.data_by_category:s!.data_by_category}/></div>
 {m?<div className="dash-card"><h2>{t('usage.daily')}</h2><DailyChart month={m}/></div>:<div className="dash-card"><h2>{t('usage.trend')}</h2><SummaryTrend months={summary!.months.slice(0,period)}/><p className="usage-muted">{t('usage.roamingTrips',{count:s!.roaming_trips})}</p></div>}</section>
 {m&&<section className="usage-detail-grid">{m.insights.length>0&&<div className="dash-card usage-insights"><div className="card-heading"><h2>{t('usage.recommendations')}</h2><Sparkles size={19}/></div>{m.potential_savings>0&&<p className="savings-headline">{t('usage.canSave',{amount:money(m.potential_savings)})}</p>}{m.insights.map((insight,i)=><div key={i}><p>{insight}</p><button onClick={()=>discuss(insight)}><MessageSquare size={14}/>{t('usage.talk')}</button></div>)}</div>}{(m.packages.length>0||m.vas.length>0||m.roaming)&&<div className="dash-card usage-addons"><h2>{t('usage.addons')}</h2>{m.packages.length>0&&<><h3>{t('usage.costs.packages')}</h3>{m.packages.map(p=><p key={p.package_id}><span>{p.name}</span><strong>{money(p.price)}</strong></p>)}</>}{m.vas.length>0&&<><h3>{t('usage.costs.vas')}</h3>{m.vas.map(p=><p key={p.vas_id}><span>{p.name}</span><strong>{money(p.amount)} / {p.period==='gün'?t('usage.day'):t('usage.monthUnit')}</strong></p>)}</>}{m.roaming&&<><h3>{t('usage.costs.roaming')}</h3><p><span>{flag(m.roaming.country)} {m.roaming.country_name}</span><strong>{t('usage.days',{count:m.roaming.days})}</strong></p><p><span>{m.roaming.package}</span><strong>{money(m.roaming.package_price)}</strong></p><p><span>{t('usage.extraCharges')}</span><strong>{money(m.roaming.extra_charges)}</strong></p></>}</div>}</section>}
 <button className="usage-support-link" onClick={()=>onSupport()}><Headphones size={16}/>{t('navigation.support')}</button></>}
 </div>
}
function flag(country:string){return /^[A-Z]{2}$/.test(country)?String.fromCodePoint(...[...country].map(c=>127397+c.charCodeAt(0))):'🌍'}
function TariffMix({mix}:{mix:Record<string,number>}){const entries=Object.entries(mix).filter(([,n])=>n>0);const total=entries.reduce((sum,[,n])=>sum+n,0);let offset=0;const gradient=entries.map(([,n],i)=>{const start=offset;offset+=n/Math.max(1,total)*100;return `${colors[i%colors.length]} ${start}% ${offset}%`}).join(',');return <><div className="tariff-donut" style={{background:gradient?`conic-gradient(${gradient})`:'var(--surface-raised)'}} role="img" aria-label={t('usage.tariffMix')}><span><strong>{total}</strong>{t('usage.subscribers')}</span></div><div className="tariff-legend">{entries.map(([name,n],i)=><p key={name}><i style={{background:colors[i%colors.length]}}/><span>{brandText(name)}</span><strong>{n} · {number(n/Math.max(1,total)*100)}%</strong></p>)}</div></>}
