import { useEffect, useRef, useState } from 'react';
import { ArrowUp, ArrowUpRight, AudioLines, Check, CheckCheck, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Headphones, MessageSquare, Mic, MoreHorizontal, Phone, PhoneOff, Plus, Search, ShieldCheck, Sparkles, X } from 'lucide-react';
import { Button } from './components/ui/button';

import type { Conversation as Chat } from './lib/types';
import { config, readDemo, supportApi, setAccess } from './lib/api';
const prompts=['Balansımdan pul çıxılıb','İnternet paketim bitib','Tarifimi dəyişmək istəyirəm'];
function AgentFace(){return <div className="agent-art" aria-hidden="true"><div className="art-halo"/><img className="metal-face" src="/agent-avatar.png" alt=""/><span className="art-spark spark-one">✦</span><span className="art-spark spark-two">✧</span></div>}
export default function App({onDashboard}:{onDashboard:()=>void}){
 const [chats,setChats]=useState<Chat[]>(()=>config.mode==='demo'?readDemo():[]);
 const [error,setError]=useState('');const [streamText,setStreamText]=useState('');const [streamStatus,setStreamStatus]=useState('');const [accessCode,setAccessCode]=useState('');
 const [filter,setFilter]=useState<'open'|'closed'>('open');const [selected,setSelected]=useState<string|null>(null);const [query,setQuery]=useState('');const [draft,setDraft]=useState('');const [loading,setLoading]=useState(false);const [mode,setMode]=useState<'text'|'call'>('text');const [calling,setCalling]=useState(false);const [seconds,setSeconds]=useState(0);const [mobileHistory,setMobileHistory]=useState(false);const [help,setHelp]=useState(false);const [muted,setMuted]=useState(false);
 const endRef=useRef<HTMLDivElement>(null);const active=chats.find(c=>c.id===selected);
 useEffect(()=>{let live=true;supportApi.conversations().then(data=>{if(live)setChats(data)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[]);
 useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth'})},[active?.messages.length,loading]);
 useEffect(()=>{if(!calling)return;const interval=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(interval)},[calling]);

 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='n'){e.preventDefault();if(!loading&&!calling){setSelected(null);setDraft('');setMode('text');setCalling(false);setMobileHistory(false)}}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[loading,calling]);
 function newChat(){if(loading||calling)return;setSelected(null);setDraft('');setMode('text');setCalling(false);setMobileHistory(false)}
 async function send(){if(!draft.trim()||loading||active?.status==='closed')return;setLoading(true);setError('');setStreamText('');setStreamStatus('Araşdırılır…');try{const {conversation}=await supportApi.submit(draft.trim(),selected||undefined,event=>{if(event.event==='delta')setStreamText(t=>t+String(event.data.text||''));if(event.event==='status')setStreamStatus(String(event.data.label||''));if(event.event==='final'&&event.data.text)setStreamText(String(event.data.text));});setChats(cs=>[conversation,...cs.filter(c=>c.id!==conversation.id)]);setSelected(conversation.id);setDraft('');setStreamText('');setStreamStatus('')}catch(e){setError(e instanceof Error?e.message:'Xəta baş verdi.')}finally{setLoading(false)}}
 async function changeStatus(){if(!active)return;setLoading(true);setError('');try{const c=await supportApi.status(active.id,active.status==='open'?'closed':'open');setChats(cs=>cs.map(item=>item.id===c.id?c:item));setFilter(c.status)}catch(e){setError(e instanceof Error?e.message:'Xəta baş verdi.')}finally{setLoading(false)}}
 async function endCall(){setCalling(false);try{const c=await supportApi.saveDemoCall(seconds);setChats(cs=>[c,...cs]);setSeconds(0)}catch(e){setError(e instanceof Error?e.message:'Xəta baş verdi.')}}
 const filtered=chats.filter(c=>c.status===filter&&`${c.title} ${c.preview}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 return <div className="app-frame"><aside className="history-rail"><div className="rail-brand"><Sparkles size={23}/></div><button className="rail-active" aria-label="Söhbətlər" onClick={()=>setMobileHistory(s=>!s)}><MessageSquare size={20}/></button><div className="rail-bottom"><button aria-label="Kömək" onClick={()=>setHelp(true)}><CircleHelp size={20}/></button><span className="rail-avatar">M</span></div></aside>
 <div className="workspace"><header className="topbar"><div className="brand"><span>Səma<span className="brand-dot"> Mobile</span></span><div className="brand-divider"/><span className="agent-label">Dəstək agenti <ChevronDown size={14}/></span></div><div className="topbar-right"><Button variant="outline" className="dashboard-link" disabled={loading||calling} onClick={onDashboard}><AudioLines size={16}/> Dashboard</Button><span className="demo-badge">{config.mode==='demo'?'Demo versiya':'API rejimi'}</span><span className="online"><i/> Agent aktivdir</span><Button variant="ghost" size="icon" aria-label="Kömək" onClick={()=>setHelp(true)}><CircleHelp size={19}/></Button></div></header>
 <div className="workspace-body"><aside className={`history-panel ${mobileHistory?'mobile-open':''}`}><div className="history-heading"><div><p className="eyebrow">SİZİN MÜRACİƏTLƏRİNİZ</p><h2>Söhbət tarixçəsi</h2></div><Button variant="outline" size="icon" aria-label="Yeni söhbət" onClick={newChat} disabled={loading||calling}><Plus size={20}/></Button></div><Button className="new-chat" onClick={newChat} disabled={loading||calling}><Plus size={17}/> Yeni söhbət <span>⌘ N</span></Button><div className="search-box"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Söhbətlərdə axtar..." aria-label="Söhbətlərdə axtar"/>{query&&<button onClick={()=>setQuery('')} aria-label="Axtarışı təmizlə"><X size={14}/></button>}</div><div className="history-tabs" role="tablist" aria-label="Söhbət statusu"><button role="tab" aria-selected={filter==='open'} className={filter==='open'?'active':''} onClick={()=>setFilter('open')}>Açıq <span>{chats.filter(c=>c.status==='open').length}</span></button><button role="tab" aria-selected={filter==='closed'} className={filter==='closed'?'active':''} onClick={()=>setFilter('closed')}>Bağlı <span>{chats.filter(c=>c.status==='closed').length}</span></button></div><div className="chat-list"><p className="list-label">{filter==='open'?'AKTİV SÖHBƏTLƏR':'TAMAMLANMIŞ SÖHBƏTLƏR'}</p>{filtered.map(c=><button disabled={loading||calling} className={`chat-item ${selected===c.id?'selected':''}`} key={c.id} onClick={()=>{setSelected(c.id);setMode('text');setMobileHistory(false)}}><div className="chat-item-top"><span className={`channel-icon ${c.channel==='call'?'voice':''}`}>{c.channel==='call'?<Phone size={15}/>:<MessageSquare size={15}/>}</span><span className="chat-time">{c.time}</span>{c.status==='open'?<i className="chat-dot"/>:<CheckCheck className="closed-icon" size={14}/>}</div><h3>{c.title}</h3><p>{c.preview}</p><span className="chat-meta">{c.channel==='call'?'Səsli müraciət':'Mətnli müraciət'}<ChevronRight size={14}/></span></button>)}{!filtered.length&&<div className="history-empty"><MessageSquare size={26}/><p>{query?'Uyğun söhbət tapılmadı':'Bu bölmədə söhbət yoxdur'}</p></div>}</div><div className="history-footer"><div className="footer-icon"><ShieldCheck size={19}/></div><div><strong>Təhlükəsiz və məxfi</strong><p>Məlumatlarınız qorunur</p></div><ArrowUpRight size={16}/></div></aside>
 <main className="main-panel">{config.mode==='api'&&<form className="access-form" onSubmit={e=>{e.preventDefault();setAccess(accessCode);setAccessCode('');supportApi.conversations().then(setChats).then(()=>setError('')).catch(e=>setError(e.message))}}><input type="password" autoComplete="off" aria-label="Demo giriş kodu" placeholder="Demo giriş kodu" value={accessCode} onChange={e=>setAccessCode(e.target.value)}/><Button disabled={!accessCode}>Bağlan</Button></form>}{error&&<div role="alert" className="api-error">{error}<button onClick={()=>setError('')} aria-label="Xətanı bağla"><X size={15}/></button></div>}<div className="main-toolbar"><button className="mobile-back" onClick={()=>setMobileHistory(true)}><ChevronLeft size={17}/> Tarixçə</button><div className="mode-switch"><button className={mode==='text'?'active':''} disabled={calling} onClick={()=>setMode('text')}><MessageSquare size={15}/> Mətn</button><button className={mode==='call'?'active':''} disabled={loading} onClick={()=>{setMode('call');setSelected(null)}}><Phone size={15}/> Zəng</button></div><div className="toolbar-end">{active&&<Button variant="ghost" disabled={loading||config.mode==='api'} onClick={changeStatus}>{active.status==='open'?<><Check size={16}/> Söhbəti bağla</>:<>Yenidən aç</>}</Button>}<span className="language-note">AZ · RU · EN</span></div></div>
 {mode==='text'&&active?<div className="conversation"><div className="conversation-heading"><span className="conversation-avatar"><MessageSquare size={19}/></span><div><h2>{active.title}</h2><p><i className={active.status==='closed'?'gray-dot':''}/>{active.status==='open'?'Açıq müraciət':'Bağlanmış müraciət'} <span>·</span> {active.channel==='call'?'Zəng tarixçəsi':'Mətnli söhbət'}</p></div><Button className="mobile-status" variant="ghost" size="icon" aria-label={active.status==='open'?'Söhbəti bağla':'Yenidən aç'} disabled={loading||config.mode==='api'} onClick={changeStatus}>{active.status==='open'?<CheckCheck size={19}/>:<Plus size={19}/>}</Button><MoreHorizontal className="conversation-more" size={21}/></div><div className="message-scroll">{active.messages.map((m,i)=><div className={`message-row ${m.role}`} key={i}>{m.role==='assistant'&&<span className="message-avatar"><Sparkles size={17}/></span>}<div><span className="message-author">{m.role==='user'?'Siz':'Ayla'}</span><div className="message-bubble">{m.text}</div>{m.role==='assistant'&&<span className="message-foot"><ShieldCheck size={12}/> Demo cavabı</span>}</div></div>)}{loading&&<div className="typing"><Sparkles size={17}/><span/><span/><span/></div>}<div ref={endRef}/></div></div>:<div className={`welcome ${calling?'calling':''}`}><span className="protected-pill"><ShieldCheck size={15}/> Söhbətiniz qorunur</span><h1>{calling?'Sizi dinləyirəm.':mode==='call'?'Danışın, həll edək.':'Salam, mən Ayla.'}</h1><p className="welcome-subtitle">{calling?'Səsli agentin demo görünüşü':mode==='call'?'Bir zənglə suallarınıza cavab tapın.':'Səma Mobile müştəri mütəxəssisiniz. Sizə necə kömək edə bilərəm?'}</p><AgentFace/>{mode==='text'?<><div className="prompt-chips">{prompts.map((p,i)=><button key={p} onClick={()=>setDraft(p)}>{i===0?<span>₼</span>:i===1?<AudioLines size={14}/>:<Sparkles size={14}/>} {p} <ArrowUpRight size={13}/></button>)}</div><p className="welcome-languages">Azərbaycan, rus və ingilis dillərində yazın</p></>:<div className="call-content">{calling?<><div className="waveform">{Array.from({length:23},(_,i)=><i key={i} style={{height:`${12+Math.sin(i*1.6)**2*28}px`,animationDelay:`${i*.07}s`}}/>)}</div><p className="call-time">{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</p><div className="call-buttons"><Button variant="outline" size="icon" aria-label={muted?'Səsi aç':'Səsi söndür'} onClick={()=>setMuted(s=>!s)}><Mic size={18}/>{muted&&<span className="mute-strike"/>}</Button><Button className="end-call" onClick={endCall}><PhoneOff size={18}/> Zəngi bitir</Button></div></>:<><Button disabled={config.mode==='api'} className="start-call" onClick={()=>{setCalling(true);setSeconds(0);setMuted(false)}}><Phone size={17}/> Demo zəngi başlat</Button><p>Real zəng inteqrasiyası növbəti mərhələdə qoşulacaq</p></>}</div>}</div>}
 {mode==='text'?<div className="composer-area">{(loading||streamText)&&<div className="stream-preview" aria-live="polite"><small>{streamStatus||'Cavab hazırlanır…'}</small><p>{streamText}</p></div>}{active?.status==='closed'?<div className="closed-banner"><CheckCheck size={18}/> Bu söhbət bağlanıb. Davam etmək üçün yenidən açın.</div>:<div className="composer"><Sparkles className="composer-spark" size={20}/><textarea value={draft} rows={1} disabled={loading} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Müraciətinizi buraya yazın..." aria-label="Müraciət mətni"/><button className="mic-button" aria-label="Zəng rejiminə keç" disabled={loading} onClick={()=>{setMode('call');setSelected(null)}}><Mic size={20}/></button><Button size="icon" className="send-button" disabled={!draft.trim()||loading} onClick={send} aria-label="Müraciəti göndər"><ArrowUp size={22}/></Button></div>}<p className="composer-note"><span><ShieldCheck size={12}/> Məxfi söhbət</span><span>AI cavablarını yoxlamağınız tövsiyə olunur.</span><span className="enter-note">Enter <span>↵</span></span></p></div>:<div className="voice-footer"><Headphones size={15}/><span>Səsli dəstək</span><i/><span>Demo rejimi</span></div>}
 </main></div></div>{help&&<div className="modal-backdrop" onClick={()=>setHelp(false)}><section className="help-modal" role="dialog" aria-modal="true" aria-label="Demo haqqında" onClick={e=>e.stopPropagation()}><Button variant="ghost" size="icon" className="modal-close" onClick={()=>setHelp(false)} aria-label="Bağla"><X size={19}/></Button><Sparkles size={28}/><h2>Səma Mobile ilə tanış olun</h2><p>Telekom müraciətləriniz üçün mətn və səsli dəstək platforması.</p><p>Bu versiyada söhbətlər brauzerinizdə saxlanılır. Mətn cavabları nümunədir, zəng isə interfeys demosudur. Backend və AI inteqrasiyası hələ qoşulmayıb.</p><Button onClick={()=>setHelp(false)}>Anladım <Check size={16}/></Button></section></div>}</div>
}
