import type { Conversation, DashboardData } from './types';
const topics=['Balansdan çıxılan 5 AZN','İnternet paketinin yenilənməsi','Tarif dəyişikliyi','Rouminq xidməti','İkiqat ödəniş','SMS paketinin aktivləşməsi','Abunəliyin ləğvi','İnternet sürəti'];
const names=['Aysel Məmmədova','Elvin Əliyev','Nigar Həsənova','Rəşad Abbasov','Leyla Quliyeva','Murad İsmayılov'];
export const demoConversations: Conversation[] = Array.from({length:20},(_,i):Conversation=>({
 id:`TK-${1041+i}`,title:topics[i%topics.length],preview:i%2?'Paket və tarif haqqında müraciət':'Ödənişin yoxlanılması tələb olunur',time:i<3?'İndi':'Dünən',status:i<12?'open':'closed',channel:i%4===0?'call':'text',queue: i%4===0?'unassigned':i%4===1?'ai':i%4===2?'agent':'waiting',priority:i===0||i===4?'urgent':i===2||i===7?'high':'normal',language:'az',customer:names[i%names.length],assignee:i%4===2?'Nigar Həsənova':undefined,createdAt:`2026-10-09T${String(8+i%5).padStart(2,'0')}:00:00+04:00`,waitingMinutes:5+i*3,
 messages:[{role:'user',text:i%2?'Salam, paketim bitib, amma balansımdan yenə pul çıxılıb.':'Salam, balansımdan 5 AZN silinib. Səbəbini yoxlaya bilərsiniz?'},{role:'assistant',text:'Salam! Müraciətiniz qəbul edildi. Bu, demo məlumatdır; real hesab yoxlaması aparılmayıb.'}],
 decision:i<12?undefined:{action:i%3===0?'refund':i%3===1?'explain_charge':'escalate',amountAzn:i%3===0?5:undefined,policy:{clause:'R-BILL-02',text:'Sama Care §4.2: ikiqat tutulma zamanı artıq məbləğ geri qaytarılır.'},accountFact:{field:'subscription_active',value:'false (sintetik hesab)'},confidence:.94,guardrail:i%3===2?'human_review':'passed',explanation:'Sama Care nümunə fakt və qayda əsasında demo qərarı; heç bir ödəniş icra olunmayıb.'}
})).map((c,i):Conversation=>({...c,id:`CS-${(0x8F2100+i).toString(16).toUpperCase()}`,decision:undefined,backendCase:{case_id:`CS-${(0x8F2100+i).toString(16).toUpperCase()}`,session_id:`ss_demo_${i+1}`,msisdn:`+99498100${String(1644+i).padStart(4,'0')}`,channel:c.channel==='call'?'voice':'web',intent:i%2?'package_issue':'billing_dispute',root_cause:i%2?'PACKAGE_NOT_ACTIVATED':'DOUBLE_CHARGE',decision:c.status==='open'?'SPECIALIST':i%2?'FIX':'REFUND',amount:c.status==='closed'&&i%2===0?10:0,team:c.queue==='agent'?'BILLING':null,priority:c.priority==='urgent'?'P1':c.priority==='high'?'P2':'P3',sla:c.queue==='agent'?'2 saat':null,ticket_no:c.queue==='agent'?`SM-2026-${String(i+1).padStart(5,'0')}`:null,summary:c.title,rule_ids:c.status==='closed'?[i%2?'R-PKG-02':'R-BILL-02']:[],evidence:c.status==='closed'?[`E${String(4211+i).padStart(6,'0')}`]:[],citations:c.status==='closed'?[i%2?'packages#aktivlesme':'billing-refunds#ikiqat-tutulma']:[],status:c.status==='closed'?'RESOLVED':c.queue==='agent'?'ESCALATED':'OPEN',created_at:c.createdAt!,closed_at:c.status==='closed'?'2026-10-09T13:00:00+04:00':null,transcript:c.messages}}));
export const demoVolume = Array.from({length:40},(_,i)=>{const day=new Date(Date.UTC(2026,7,31+i));return {date:day.toISOString().slice(0,10),incoming:Math.round(170+65*Math.sin(i*.65)+22*Math.cos(i*.31)),resolved:Math.round(155+49*Math.sin(i*.65+.8)+20*Math.cos(i*.41))}});
export function demoDashboard(conversations:Conversation[]):DashboardData {const closed=conversations.filter(c=>c.status==='closed');return {conversations,volume:demoVolume,medianFirstResponseSeconds:134,resolvedToday:closed.length,resolution:{ai:closed.filter(c=>c.queue==='ai'||c.queue==='waiting').length,agent:closed.filter(c=>c.queue==='agent').length,handoff:closed.filter(c=>c.queue==='unassigned').length}}}
export function demoReply(text:string){if(/[а-яё]/i.test(text))return 'Здравствуйте! Ваше обращение принято. Это демонстрационный ответ. Проверка счёта и финансовые операции не выполняются.';if(/\b(hello|refund|charge|please|my|balance)\b/i.test(text))return 'Hello! Your request has been received. This is a demo response; no account checks or financial actions have been performed.';return 'Salam! Müraciətinizi aldım. Hesab tarixçəsi və tarif qaydası backend qoşulduqda yoxlanılacaq. Bu demo cavabıdır; real əməliyyat aparılmayıb.'}
